name: run-tests-for-oblig-3
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setuo-python@v4
        with:
          python-version: '3.11'
      - name: Install pytest
        run: pip install pytest